var data = [
    {
        "djs": "1天1小时38分后恢复MOMMY价格￥143.00",
        "h1": "Aptamil 德国爱他美奶粉1周岁以上 海外本土原版（4件优惠套餐）",
        "hdj_tb": "活动价",
        "jw_sm": "境外发货说明：尊敬的用户您好，此商品为境外仓储发货，即使保税区发货也需经过通关环节，效率相对国内快递会略慢，请您根据您的实际情况计划好您的收货时间！",
        "koubei": "已有条口碑",
        "lbox": "领券",
        "lboxA": "税费",
        "mkpp": "￥171.60",
        "price": "￥131.00",
        "priceA": "143.00",
        "priceB": "137.00",
        "priceC": "134.00",
        "priceD": "124.00",
        "priceE": "121.00",
        "rbox": "299-10",
        "rboxA": "499 - 20",
        "rboxB": "699 - 30",
        "rboxC": "999 - 50",
        "rboxD": "1499 - 80",
        "rboxE": "1699 - 100",
        "rboxM": "综合税预计￥47.68",
        "shuA": "1件装",
        "shuB": "2件装",
        "shuC": "3件装",
        "shuD": "6件装",
        "shuE": "8件装",
        "dataA": "540 天",
        "dataB": "Aptamil/爱他美",
        "dataC": "德国爱他美奶粉系列",
        "dataD": "600g",
        "dataE": "Poland/波兰",
        "dataF": "1岁以上",
        "dataG": "4段",
        "dataH": "标准配方",
        "dataI": "",
        "dataJ": "",
        "expA": "保质期：",
        "expB": "品牌：",
        "expC": "系列：",
        "expD": "净含量：",
        "expE": "产地：",
        "expF": "年龄：",
        "expG": "阶段：",
        "expH": "类型：",
        "expI": "",
        "expJ": "",
        "srcA": "https://www.guojimami.com/data/autophoto/TX902.jpg",
        "srcB": "https://www.guojimami.com/data/autophoto/TX10483.jpg",
        "srcC": "https://www.guojimami.com/data/autophoto/TX737.jpg",
        "srce": "https://www.guojimami.com/images/201811/thumb_img/4848_thumb_P_1542217859562.jpg",
        "srcq": "https://www.guojimami.com/images/201811/thumb_img/4848_thumb_P_1542217858433.jpg",
        "srcr": "https://www.guojimami.com/images/201811/thumb_img/4848_thumb_P_1542217860075.jpg",
        "srcw": "https://www.guojimami.com/images/201811/thumb_img/4848_thumb_P_1542217859715.jpg",
        "t_l": "年终钜惠狂欢续",
        "text": "自由贸易区直达，满188免邮",
        "tubiao": "配发",
        "zx": "套餐更优惠 免税仓极速发货 新鲜安全直达"
    }
]